model:
  provider: "anthropic"
  name: "claude-sonnet-4-20250514"

agent:
  max_tools: 20
  timeout_sec: 60
  allow_network: false

react_demo:
  target_number: 5
  max_cycles: 10

workspace:
  base_dir: ".runs"

dataset:
  description: "US Natural Gas Pipeline Transportation Data - Comprehensive dataset containing 23,854,855 records spanning 3.7 years (January 2022 to August 2025) across 169 pipeline companies, 17,528 delivery locations, and 48 states. Includes daily gas scheduling operations with receipt/delivery indicators, transaction categories, geographic data, and scheduled quantities."
  path: "data/pipeline_data.parquet"
  analysis_file: "/Users/user/Projects/claude_data_agent/docs/2025_09_22_17_31_preliminary_data_analysis.md"

judging:
  enabled: true
  model: "anthropic:claude-3-5-haiku-20241022"  # Cost-effective model for judging
  template: "templates/judging_prompt.txt"
  timeout_sec: 30
  score_threshold: 3.0  # Minimum score to consider response acceptable

# Environment variables are loaded from .env file
# ANTHROPIC_API_KEY and OPENAI_API_KEY should be set there